---
params:
  pid: "Patient"
title: "ddPCR laboratory results"
fontsize: 10pt
geometry: margin=1cm
fig_width: 8
fig_height: 6
output:
  pdf_document:
    keep_tex: false
    toc: false
    highlight: zenburn
header-includes:
- \usepackage{fancyhdr}
- \usepackage{lastpage}
- \usepackage{xcolor}
- \usepackage{tabularx}
- \usepackage{caption}

---
\definecolor{darkgreen}{HTML}{188a06}
\definecolor{darkbrown}{HTML}{A52A2A}

\large\textbf{\underline{KAPA Library Quantification}}

\textbf{\underline{Standard Curve (Set 1)}}

\textbf{Experiment Information}

\begin{tabular}{l l}
File name: & B1 \\
Run started & B5 \\
Run ended & B6 \\
Machine used: & Machine \\
\end{tabular}

\textbf{Quantification Information}

\begin{tabular}{|c | c | c |}
Parameter & Results & QC Status \\
Threshold &         &           \\
Slope     &         &           \\
Reaction efficiency &  &        \\
$R^2$ Value   &         &           \\
\end{tabular} 

\textbf{Quantification Results} 

\textbf{Quality Control (QC) Checklist}


\begin{tabular} {|c l c|}
No. & Quality Control Criteria & QC Status \\
1   & Slope between -3.1 and -3.6 &        \\
2   & Reaction Efficiency 90\%-110\% &       \\
3   & $R^2$ value: $\geq$0.99     &       \\
4   & $\Delta$Ct of replicates within $\pm$1.5 & \\
5   & $\Delta$Ct of Average Ct between consecutive Standards: 3.1 to 3.6 & \\
6   & Lowest Ct of NTC $\geq$3.0 Ct from highest Ct of Standard 6       & \\
Overall QC Status & 1  & \\
\end{tabular} 

